baseURL = 'https://amlwwalker.github.io/neo-docs/'
languageCode = 'en-us'
title = 'Neo FS Tutorials'
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
[params]
landingPageURL='/neo-docs/'
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "green"
#landingPageURL = 'https://amlwwalker.github.io/neo-docs/'
# For search functionality
[Languages]
[Languages.en]
weight = 1
title = "English"
[Languages.en.params]
linkedin = "english-link"

[Languages.fr]
weight = 2
title = "Français"
[Languages.fr.params]
linkedin = "lien-francais"

[outputs]
home = [ "HTML", "RSS", "JSON"]
